### ISSUE TITLE
Version 2.0 vs. 2.2

### ISSUE THREAD

**Issue by Preacher** [elevation/event_calendar#15]
I had to download v2.0 and install it to get this to work in Rails 2.3.8. It seems some of the generators got broke when you made it compatible with Rails 3. Just a heads up.

**Comment by jeffschuil** [comment]
What exactly isn't working for you in the latest version? Do you get stuck at a certain point, or get an error message?

When I create a new rails 2.3.8 project, install the plugin, and run the generator, it appears to work correctly. Thanks for the help.

**Comment by Preacher** [comment]
```
    [User@server test_app]$ rake db:create
    (in /home/User/test_app)
    [User@server test_app]$ ruby script/plugin install git://github.com/elevation/event_calendar.git
    Initialized empty Git repository in .git/
    warning: no common commits
    remote: Counting objects: 64, done.
    remote: Compressing objects: 100% (53/53), done.
    remote: Total 64 (delta 19), reused 0 (delta 0)
    Unpacking objects: 100% (64/64), done.
    [User@server test_app]$ ruby script/generate event_calendar
    /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require': no such file to load -- rails/generators/migration (MissingSourceFile)
            from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `block in require'
            from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in `new_constants_in'
            from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
            from /home/User/test_app/vendor/plugins/event_calendar/lib/generators/event_calendar/event_calendar_generator.rb:1:in `<top (required)>'
            from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
            from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `block in require'
            from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in `new_constants_in'
            from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
            from /usr/local/lib/ruby/gems/1.9.1/gems/rails-2.3.8/lib/rails_generator/spec.rb:17:in `klass'
            from /usr/local/lib/ruby/gems/1.9.1/gems/rails-2.3.8/lib/rails_generator/lookup.rb:140:in `instance'
            from /usr/local/lib/ruby/gems/1.9.1/gems/rails-2.3.8/lib/rails_generator/scripts.rb:31:in `run'
            from /usr/local/lib/ruby/gems/1.9.1/gems/rails-2.3.8/lib/commands/generate.rb:6:in `<top (required)>'
            from script/generate:3:in `require'
            from script/generate:3:in `<main>'
    [User@server test_app]$
```

Downloading, extracting, and installing v2.0 has worked just fine. Now I'm fiddling around getting it to work the way I want with my role-base authorization/authentication.

Thanks for the quick reply. I wasn't too worried about it, because I got 2.0 working.

**Comment by jeffschuil** [comment]
Yours does appear to be trying to use the new generators in ../lib/generators, rather than the old ones in ../generators. I'm not sure why. Maybe mine is working because I still have Rails 3 installed.

As you figured out you can still run the old, tagged versions. It shouldn't matter too much, but 2.2 was the last tag before the Rails 3 generators were added. For reference, people can install it with:

script/plugin install git://github.com/elevation/event_calendar.git -r 'tag 2.2'

**Comment by Preacher** [comment]
k, thanks a lot, and good work.
