### ISSUE TITLE
Rails 2.3.8 generator failed 

### ISSUE THREAD

**Issue by bublik** [elevation/event_calendar#20]
[wr@bublik rubyclub]$ script/generate event_calendar  
/home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems.rb:233:in `activate': can't activate activesupport (= 3.0.0.beta3, runtime) for ["railties-3.0.0.beta3"], already activated activesupport-2.3.8 for ["rails-2.3.8"] (Gem::LoadError)
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems.rb:249:in`activate'
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems.rb:248:in `each'
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems.rb:248:in`activate'
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:35:in `require'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in`require'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in `new_constants_in'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in`require'
        from /home/wr/Public/rubyclub/vendor/plugins/event_calendar/lib/generators/event_calendar/event_calendar_generator.rb:1
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in`new_constants_in'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.8/lib/rails_generator/spec.rb:17:in`klass'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.8/lib/rails_generator/lookup.rb:140:in `instance'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.8/lib/rails_generator/scripts/../scripts.rb:31:in`run'
        from /home/wr/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.8/lib/commands/generate.rb:6
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /home/wr/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from script/generate:3

**Comment by movihus** [comment]
I Confirm this error. Same here.

 script/generate event_calendar
 /usr/local/lib/site_ruby/1.8/rubygems.rb:242:in `activate': can't activate activesupport (= 3.0.3, runtime) for ["railties-3.0.3"], already activated activesupport-2.3.8 for ["rails-2.3.8"] (Gem::LoadError)
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:258:in`activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in `each'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in`activate'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:33:in `require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in`require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in`require'
    from /home/movihus/code/repo/directorio/trunk/vendor/plugins/event_calendar/lib/generators/event_calendar/event_calendar_generator.rb:1
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in`new_constants_in'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.8/lib/rails_generator/spec.rb:17:in`klass'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.8/lib/rails_generator/lookup.rb:140:in `instance'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.8/lib/rails_generator/scripts/../scripts.rb:31:in`run'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.8/lib/commands/generate.rb:6
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'
    from script/generate:3
