### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by rurounijones** [elevation/event_calendar#24]
Rails 2.3.5 on Ruby 1.8.7 - After installing the plugin the generator fails

```
script/generate event_calendar Event CalendarController --user-jquery
 /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- rails/generators/migration (MissingSourceFile)
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /home/jjones/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /home/jjones/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /home/jjones/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /home/jjones/Development/web/Agensys/vendor/plugins/event_calendar/lib/generators/event_calendar/event_calendar_generator.rb:1
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /home/jjones/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /home/jjones/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /home/jjones/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /home/jjones/.gem/ruby/1.8/gems/rails-2.3.5/lib/rails_generator/spec.rb:17:in `klass'
    from /home/jjones/.gem/ruby/1.8/gems/rails-2.3.5/lib/rails_generator/lookup.rb:140:in `instance'
    from /home/jjones/.gem/ruby/1.8/gems/rails-2.3.5/lib/rails_generator/scripts/../scripts.rb:31:in `run'
    from /home/jjones/.gem/ruby/1.8/gems/rails-2.3.5/lib/commands/generate.rb:6
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from script/generate:3
```

**Comment by jeffschuil** [comment]
Hmmm.... It looks like it is trying to run the Rails 3 generator (which requires that missing file), rather than the rails 2.3 generator. I just created a new rails 2.3.5 project, installed the plugin, and ran the generator. Everything worked. Can you think of any reason why it's running that other generator?

This is what I just tried:
1. rails test_cal
2. cd test_cal
3. script/plugin install git://github.com/elevation/event_calendar.git
4. script/generate event_calendar --use-jquery

If all else fails, you can try going back to revision 2.2, before rails 3 support was added.

script/plugin install --revision 'tag 2.2' git://github.com/elevation/event_calendar.git

**Comment by chufarj** [comment]
running rails 2.3.4, and so I also needed to install using:

script/plugin install --revision 'tag 2.2' git://github.com/elevation/event_calendar.git

**Comment by ldamman** [comment]
I had the same issue.  Thanks for the comments here!  Someone may want to update the installation instructions under "Rails 2" to include the --revision 'tag 2.2'
